Relay / GraphQL
buildkite/frontend pull request #615
Opened 2018-10-10 07:40 UTC by plasticine

OK, one more time with feeling! 😛

This is a follow up to #606 to address concerns raised around storing generated Relay files inside the repo, under version control — as discussed in the engineering catch-up this morning.

This patch reworks the strategy introduced in #606 for the GraphQL server & Relay client workflow to remove the need to store the compiled our Relay queries and types ([ref](https://facebook.github.io/relay/docs/en/graphql-in-relay.html#relay-compiler)) in the repo by generating them on the fly instead. It does not remove the pre-existing generated GraphQL schema dump (`app/graph/schema.json`). That will have to wait for another day; it’s pre-existing and changing it massively complicates our current testing infra / docker setup. 🙃

This patch introduces a new process that provides Relay compilation outside of Webpack. This is required as having a webpack handle it creates a chicken/egg problem when attempting to consume the flow types in our source code from the generated code. Compilation would never succeed if the generated files were not present, meaning that the generated could never be compiled into place. LOL.

This new process is a small(ish) node script that is booted with the rest of the development environment via `Procfile`.

It sets up watches on the filesystem for changes to both the JS source code, and also the Ruby GraphQL source code;
- **When the JS code changes:**
  - (re)compile the generated Relay files using the JS source and the schema dump.
- **When the Ruby code changes:** 
  - sync a fresh copy of the introspection schema to disk.
    - _PS: is this a problem storing this in a public repo? Are there any sensitive fields here?_ 🤔
  - (re)compile the generated Relay files using the JS source and the schema dump.

2018-10-10 17:40 UTC, ticky requested changes
Seems legit! Can we have the `watch_graph` script follow our eslints, though please? 😄

2018-10-10 17:40 UTC, ticky commented on script/watch_graph
> +/* eslint-disable */
🤔

2018-10-10 22:03 UTC, plasticine commented
> Seems legit! Can we have the watch_graph script follow our eslints, though please? 😄

Sure.

2018-10-10 22:19 UTC, plasticine commented on script/watch_graph
> +/* eslint-disable */
✅ done!

2018-10-10 22:20 UTC, ticky approved these changes

2018-10-11 00:18 UTC, sj26 commented on webpack/config.js
> -  }),
So I thought we avoided running relay-compiler manually by using this relay compiler webpack plugin, which webpack dev server and the build process run to create the required generated files. Is the trouble that these files aren't generated in time to be consumed by our own files?

2018-10-11 00:18 UTC, sj26 commented on webpack/config.js
> -  }),
Also, does webpack 4 address any of this?

2018-10-11 03:01 UTC, sj26 commented on webpack/config.js
> -  }),
I love javascript. 😭

2018-10-11 03:01 UTC, sj26 approved these changes

2018-10-11 04:18 UTC, merged